version: "2.0"

services:
  kaia-swarm:
    image: ghcr.io/wonderofme/kaia-swarm:v140
    env:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - DIRECT_PORT=3000
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    kaia-profile:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 2Gi
        storage:
          size: 1Gi

  placement:
    akash:
      pricing:
        kaia-profile:
          denom: uakt
          amount: 100

deployment:
  kaia-swarm:
    akash:
      profile: kaia-profile
      count: 1


