import nodemailer from 'nodemailer';

const FEATURE_REQUEST_EMAIL = 'tech@si3.space';

// Create reusable transporter
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT || '587'),
  secure: false, // true for 465, false for other ports
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

export async function sendFeatureRequest(
  userId: string,
  userName: string,
  userMessage: string,
  featureRequest: string
): Promise<void> {
  if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
    console.error('[Feature Request] SMTP credentials not configured, cannot send email');
    return;
  }

  const mailOptions = {
    from: process.env.SMTP_USER,
    to: FEATURE_REQUEST_EMAIL,
    subject: `Feature Request from ${userName || 'User'} (${userId})`,
    text: `A user has submitted a feature request through Agent Kaia.

User ID: ${userId}
User Name: ${userName || 'Not provided'}
Original Message: ${userMessage}

Feature Request:
${featureRequest}

---
This email was automatically generated by Agent Kaia.`,
    html: `
      <h2>Feature Request from Agent Kaia</h2>
      <p><strong>User ID:</strong> ${userId}</p>
      <p><strong>User Name:</strong> ${userName || 'Not provided'}</p>
      <p><strong>Original Message:</strong> ${userMessage}</p>
      <hr>
      <h3>Feature Request:</h3>
      <p>${featureRequest.replace(/\n/g, '<br>')}</p>
      <hr>
      <p><em>This email was automatically generated by Agent Kaia.</em></p>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`[Feature Request] ✅ Successfully sent feature request to ${FEATURE_REQUEST_EMAIL}`);
  } catch (error) {
    console.error('[Feature Request] ❌ Error sending email:', error);
    throw error;
  }
}

