import nodemailer from 'nodemailer';

const FEATURE_REQUEST_EMAIL = 'opereayoola@gmail.com';

// Create transporter function - create it fresh each time to ensure env vars are current
function createTransporter() {
  const smtpHost = process.env.SMTP_HOST || 'smtp.gmail.com';
  const smtpPort = parseInt(process.env.SMTP_PORT || '587');
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;

  if (!smtpUser || !smtpPass) {
    throw new Error('SMTP credentials not configured');
  }

  return nodemailer.createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: smtpPort === 465, // true for 465, false for other ports
    auth: {
      user: smtpUser,
      pass: smtpPass,
    },
  });
}

export async function sendFeatureRequest(
  userId: string,
  userName: string,
  userMessage: string,
  featureRequest: string
): Promise<void> {
  // Check if SMTP credentials are configured
  const smtpHost = process.env.SMTP_HOST || 'smtp.gmail.com';
  const smtpPort = parseInt(process.env.SMTP_PORT || '587');
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;

  if (!smtpUser || !smtpPass) {
    console.error('[Feature Request] ❌ SMTP credentials not configured');
    console.error('[Feature Request] SMTP_USER:', smtpUser ? 'SET' : 'MISSING');
    console.error('[Feature Request] SMTP_PASS:', smtpPass ? 'SET' : 'MISSING');
    throw new Error('SMTP credentials not configured. Please set SMTP_USER and SMTP_PASS environment variables.');
  }

  console.log('[Feature Request] 📧 Attempting to send email...');
  console.log('[Feature Request] SMTP_HOST:', smtpHost);
  console.log('[Feature Request] SMTP_PORT:', smtpPort);
  console.log('[Feature Request] SMTP_USER:', smtpUser);
  console.log('[Feature Request] SMTP_PASS:', smtpPass ? '***' + smtpPass.slice(-4) : 'MISSING');

  const mailOptions = {
    from: process.env.SMTP_USER,
    to: FEATURE_REQUEST_EMAIL,
    subject: `Feature Request from ${userName || 'User'} (${userId})`,
    text: `A user has submitted a feature request through Agent Kaia.

User ID: ${userId}
User Name: ${userName || 'Not provided'}
Original Message: ${userMessage}

Feature Request:
${featureRequest}

---
This email was automatically generated by Agent Kaia.`,
    html: `
      <h2>Feature Request from Agent Kaia</h2>
      <p><strong>User ID:</strong> ${userId}</p>
      <p><strong>User Name:</strong> ${userName || 'Not provided'}</p>
      <p><strong>Original Message:</strong> ${userMessage}</p>
      <hr>
      <h3>Feature Request:</h3>
      <p>${featureRequest.replace(/\n/g, '<br>')}</p>
      <hr>
      <p><em>This email was automatically generated by Agent Kaia.</em></p>
    `,
  };

  try {
    const transporter = createTransporter();
    await transporter.sendMail(mailOptions);
    console.log(`[Feature Request] ✅ Successfully sent feature request to ${FEATURE_REQUEST_EMAIL}`);
  } catch (error: any) {
    console.error('[Feature Request] ❌ Error sending email:', error);
    
    // Provide more helpful error messages
    if (error.code === 'EAUTH') {
      console.error('[Feature Request] Authentication failed. Common causes:');
      console.error('[Feature Request] 1. Using regular password instead of App Password (for Gmail)');
      console.error('[Feature Request] 2. Incorrect username or password');
      console.error('[Feature Request] 3. 2-Step Verification not enabled (for Gmail)');
      console.error('[Feature Request] 4. App Password not generated');
      throw new Error('SMTP authentication failed. Please check your SMTP credentials. For Gmail, make sure you\'re using an App Password, not your regular password.');
    } else if (error.code === 'ECONNECTION' || error.code === 'ETIMEDOUT') {
      throw new Error('Could not connect to SMTP server. Please check SMTP_HOST and SMTP_PORT settings.');
    } else {
      throw error;
    }
  }
}

